(defun json-insert-object ()
  (interactive)
  (insert "{")
  (newline)
  (newline)
  (insert "}")
  (indent-for-tab-command)
  (previous-line)
  (insert "\"\"")
  (indent-for-tab-command)
  (forward-char))
